CREATE TABLE Proyectos (
  CodP INT NOT NULL PRIMARY KEY,
  Descrip VARCHAR(20) NULL,
  Localidad VARCHAR(20) NULL,
  Cliente VARCHAR(20) NULL,
  Telefono VARCHAR(20) NULL
);

CREATE TABLE Maquinas (
  CodM INT NOT NULL PRIMARY KEY,
  Nombre VARCHAR (20) NULL,
  PrecioHora INT NULL
);

CREATE TABLE Conductores (
  CodC INT NOT NULL PRIMARY KEY,
  Nombre VARCHAR(20) NULL,
  Localidad VARCHAR(20) NULL,
  Categ SMALLINT NULL
);

CREATE TABLE Trabajos (
  CodT INT NOT NULL PRIMARY KEY,
  CodC INT NOT NULL,
  CodM INT NOT NULL,
  CodP INT NOT NULL,
  Fecha DATE NOT NULL,
  Tiempo SMALLINT NULL
);
