CREATE TABLE cervezas (
  CodC INT NOT NULL PRIMARY KEY,
  Envase VARCHAR(10) NOT NULL,
  Capacidad DECIMAL (5,2) NOT NULL,
  Stock SMALLINT
);

CREATE TABLE bares (
  CodB INT NOT NULL PRIMARY KEY,
  Nombre VARCHAR(15) NOT NULL,
  Cif VARCHAR(11),
  Localidad VARCHAR(15)
);

CREATE TABLE empleados (
  CodE INT NOT NULL PRIMARY KEY,
  Nombre VARCHAR(20) NOT NULL,
  Sueldo INTEGER
);

CREATE TABLE reparto (
  CodR INT NOT NULL PRIMARY KEY,
  CodE INT NOT NULL,
  CodB INT NOT NULL,
  CodC INT NOT NULL,
  Fecha DATE NOT NULL,
  Cantidad SMALLINT
);